---


- name: Restart AI Worker service
  systemd:
    state: restart
    daemon_reload: yes
    name: "{{ worker_service_name }}"
    enabled: True
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[worker_username].1 }}"
  become_user: "{{ worker_username }}"
  when: not service_started.changed
  tags: 
  - worker
  - systemd