---

namespace: "haidra"
name: "deployments"
version: "0.1.0"
readme: "README.md"
authors:
    - Divided by Zer0 <mail@dbzer0.com>
dependencies: {}
license:
    - "MIT"
tags:
    - haidra
    - aihorde
repository: "https://github.com/Haidra-Org/deployments"
issues: "https://github.com/Haidra-Org/deployments/issues"
description: Ansible collection for Haidra deployments