galaxy_info:
  role_name: amd_gpu_drivers
  author: db0
  description: Setup AMD drivers and ROCM on a linux server
  license: AGPLv3
  min_ansible_version: 2.10
  platforms:
  - name: Debian
    versions:
    - 11
    - 12
  - name: Ubuntu
    versions:
    - 2204
    - 2404
  galaxy_tags: 
  - python
  - amd
  - drivers
dependencies: []