---

- hosts: artbot_server

  roles:
  - name: haidra.artbot
    tags: artbot
  - name: haidra.artbot_revproxy
    vars:
      artbot_domain: artbot.rocks
      artbot_server: 127.0.0.1
      email: your.email@example.com
    tags: artbot_revproxy
